-- SQLite
--CREATE TABLE initialloads (userid INT, loadid BIGINT, direction TINYTEXT, loadDate TINYTEXT, trasportType TINYTEXT, fromTown TINYTEXT, whereTown TINYTEXT, paymentInfo TINYTEXT, paymentDetails TINYTEXT, cargo VARCHAR(512));
--INSERT INTO loads (userid, loadid, direction, loadDate, trasportType, fromTown, whereTown, paymentInfo, paymentDetails, cargo) VALUES (1,1,1,1,1,1,1,1,1,1);
--SELECT * FROM loads;
--DELETE FROM loads;
--DROP TABLE initialloads;
--CREATE TABLE userlinks (userid INT, link VARCHAR(1024));
--INSERT INTO userlinks (userid, link) VALUES (478243252, 'https://lardi-trans.com/gruz/c640h640q1y1.html');
--CREATE TABLE currentloads (userid INT, loadid BIGINT, link VARCHAR(1024));
--CREATE TABLE loadsforcompare (userid INT, loadid BIGINT, link VARCHAR(1024)); 
--CREATE TABLE usermonitoring (userid INT, isMonitoring BOOLEAN);
--INSERT INTO usermonitoring (userid, isMonitoring) VALUES (478243252, 1);
--DROP TABLE initialloads;
--CREATE TABLE initialloads (userid INT, loadid BIGINT, link VARCHAR(1024)); 
--UPDATE usermonitoring SET isMonitoring=0 WHERE userid='478243252'
--SELECT loads.loadid FROM initialloads, loads WHERE loads.userid=initialloads.userid;
--UPDATE TABLE initialloads; 
--SELECT loads.loadid FROM initialloads, loads WHERE loads.loadid!=initialloads.loadid
--SELECT userid, loadid FROM loads EXCEPT SELECT userid, loadid FROM initialloads
SELECT * FROM loads EXCEPT SELECT * FROM initialloads