-- SQLite
--CREATE TABLE loads (userid INT, loadid BIGINT, direction TINYTEXT, loadDate TINYTEXT, trasportType TINYTEXT, fromTown TINYTEXT, whereTown TINYTEXT, paymentInfo TINYTEXT, paymentDetails TINYTEXT, cargo VARCHAR(512));
--INSERT INTO loads (userid, loadid, direction, loadDate, trasportType, fromTown, whereTown, paymentInfo, paymentDetails, cargo) VALUES (1,1,1,1,1,1,1,1,1,1);
--SELECT * FROM loads;
--DELETE FROM loads;
--CREATE TABLE userlinks (userid INT, link VARCHAR(1024));
--CREATE TABLE currentloads (userid INT, loadid BIGINT, link VARCHAR(1024));